# Copyright (c) 2022, NVIDIA CORPORATION. All rights reserved.
#
# Permission is hereby granted, free of charge, to any person obtaining a
# copy of this software and associated documentation files (the "Software"),
# to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense,
# and/or sell copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
# THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
# DEALINGS IN THE SOFTWARE.

CUDA_INCLUDED_DRIVER_VER = "470.82.01"

PKGSUM_MD5 = "9f43a6f15426c8cae3955d60a6d5903c"
PKGSUM_SHA256 = "a09306bf57cc09e4ac64626450dc9294efb65cd511ab3423622a68ee57ef9653"

PKGSUM_MD5:x86-64 = "1292ecc393f9f33653d794e148d9a16b"
PKGSUM_SHA256:x86-64 = "bda115eab17ecfb3eb3800baede9604644196a16666feaff23966b3692553ce8"

LIC_CHKSUM_MD5 = "141f4a034bcf51b9bf22a2aac2c7ad17"
